name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: swift-actions/setup-swift@v1

      - run: swift test
