name: Test

on:
  push:
    branches: [ main, production ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v1

      - run: swift test
