name: Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2

      - run: swift test
